- name: install first applications
  tags: ubuntu,fail2ban,curl,iotop
  apt:
    name: 
      - fail2ban
      - iotop
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      
    state: latest
  when: ansible_distribution == "Ubuntu"
  
- name: add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
      
- name: get ubuntu version
  command: "lsb_release -cs"
  register: ubuntu_version

- name: add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

- name: install Docker
  apt:
  name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - docker-buildx-plugin
  update_cache: yes
  
- name: add user permissions
  shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"
