- name: install first applications
  tags: ubuntu,fail2ban,curl,iotop
  apt:
    name: 
      - fail2ban
      - btop
      - iotop
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common      
    state: latest
  when: ansible_distribution == "Ubuntu"
  
- name: Create directory for Docker GPG keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  
  
- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570 # curl -sL https://download.docker.com/linux/ubuntu/gpg|sha256sum

- name: get ubuntu version
  command: "lsb_release -cs"
  register: ubuntu_version

- name: add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

- name: install Docker
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - docker-buildx-plugin
    state: latest
  
- name: add user permissions
  shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"
